### ISSUE TITLE
Failed to execute

### ISSUE THREAD

**Issue by mathisloge** [flathub-infra/flatpak-github-actions#14]
I wanted to use this repo instead of the original one, but as soon as I use this instead of the normal one I get the following failure: 
```
Run flathub-infra/flatpak-github-actions/flatpak-builder@master
/usr/bin/docker exec  14d939cdfb712280934[16](https://github.com/mathisloge/photobox/actions/runs/11898105487/job/33154001738#step:4:17)7dade1f2e34274b5fe724e0330ca97f18c40333a237 sh -c "cat /etc/*release | grep ^ID"
No cache was found
node:events:497
      throw er; // Unhandled 'error' event
      ^
Error: spawn dbus-daemon ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:[19](https://github.com/mathisloge/photobox/actions/runs/11898105487/job/33154001738#step:4:20))
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn dbus-daemon',
  path: 'dbus-daemon',
  spawnargs: [ '--session', '--print-address' ]
}
Node.js v[20](https://github.com/mathisloge/photobox/actions/runs/11898105487/job/33154001738#step:4:21).13.1
```

Used it as this: 

```
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:kde-6.8
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flathub-infra/flatpak-github-actions/flatpak-builder@master
        with:
          bundle: app.flatpak
          manifest-path: de.my.app.Devel.yml
          cache-key: flatpak-builder-${{ github.sha }}
          run-tests: true
```

**Comment by bbhtt** [comment]
Looks like the `dbus-daemon` binary went missing from the image used. I've queued rebuilds with it, it will take some time (5-6 hours).

**Comment by bbhtt** [comment]
Should work when https://github.com/flathub-infra/flatpak-github-actions/actions/runs/11900590827/job/33161754850 finishes.

**Comment by bbhtt** [comment]
Did this work after the above?

**Comment by mathisloge** [comment]
Sorry, thought this was closed.
The reported error is fixed. But at least in my current setup nothing is really build: 
```
Run flathub-infra/flatpak-github-actions/flatpak-builder@master
  with:
    bundle: photobox.flatpak
    manifest-path: de.matnel.photobox.Devel.yml
    cache-key: flatpak-infra-builder-8b85[2](https://github.com/mathisloge/photobox/actions/runs/12004807696/job/33460363468#step:4:2)e03a9fc2c9de807dc57584bf2c27[3](https://github.com/mathisloge/photobox/actions/runs/12004807696/job/33460363468#step:4:3)932747
    run-tests: true
    build-bundle: true
    repository-url: https://flathub.org/repo/flathub.flatpakrepo
    repository-name: flathub
    cache: true
    restore-cache: true
    branch: master
    arch: x86_6[4](https://github.com/mathisloge/photobox/actions/runs/12004807696/job/33460363468#step:4:4)
    verbose: false
    upload-artifact: true
/usr/bin/docker exec  0302dad4ffcfa164fe181[5](https://github.com/mathisloge/photobox/actions/runs/12004807696/job/33460363468#step:4:5)bbbf72ef61b2dfb9541e9fe25b3887d5ce923513bc sh -c "cat /etc/*release | grep ^ID"
No cache was found
```

And thats all what happens. However, if I'm using this image `bilelmoussaoui/flatpak-github-actions:kde-6.7` with the same configurations just another cache key, it builds and tests everything. :thinking:
